use_frameworks!
platform :ios, '9.0'

target 'FMTDebugger_Example' do
  pod 'FMTDebugger', :path => '../'
  pod 'FMTFoundation', :git => 'https://github.com/SuperMarioBean/fmtfoundation.git', :branch => 'master'
  
  target 'FMTDebugger_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
