use_frameworks!

target 'FMTDebugger_Example' do
  pod 'FMTDebugger', :path => '../'

  target 'FMTDebugger_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
